# t-test for randomization using one hot encoded data

```{r}
robust_se <- function(model){
  # get robust standard error
  sqrt(diag(vcovHC(model)))
}

d <- fread(file="../data/fb_ad_data.csv")
```

```{r one-hot encode treatment groups}
ad_codes <- c('control', 'visual', 'text', 'textvisual')
ad_groups <- c('control', 'visual treatment', 'text treatment', 'text + visual treatment')
for (i in 1:length(ad_groups)) {
  d[, ad_codes[i] := ifelse(group == ad_groups[i], 1, 0)]
}
```

```{r one-hot encode genders}
genders <- c('female', 'male')
for (i in 1:length(genders)) {
  d[, genders[i] := ifelse(gender == genders[i], 1, 0)]
}
d[, "unknown_gender" := ifelse(gender == "unknown", 1, 0)]
```

```{r one-hot encode ages}
age_codes <- c('a18_24', 'a25_34', 'a35_44', 'a45_54', 'a55_64', 'a65plus')
ages <- c('18-24', '25-34', '35-44', '45-54', '55-64', '65+')
for (i in 1:length(ages)) {
  d[, age_codes[i] := ifelse(age == ages[i], 1, 0)]
}
d[, "unknown_age" := ifelse(age == "unknown", 1, 0)]
```

```{r randomization check}
#Estimate model
m0 <- lm(textvisual + text + visual ~ female, 
         data=d[gender!= "unknown" & age != "unknown",])

m1 <- lm(textvisual + text + visual ~ female + a18_24 + a25_34 + a35_44 + a45_54 + a55_64, 
         data=d[gender!= "unknown" & age != "unknown",])

#Print results
stargazer(m0, m1, 
          se = c(list(robust_se(m0)),
                 list(robust_se(m1))),
          type = 'text')
```

```{r t-test of variables for randomness}
#Estimate model
m_simple_treat <- lm(treated ~ female + male, 
         data=d)

m_saturate_trt <- lm(treated ~ female + male + a18_24 + a25_34 + a35_44 + a45_54 + a55_64 + a65plus, 
         data=d)

#Print results
stargazer(m_simple_treat, m_saturate_trt, 
          se = c(list(robust_se(m_simple_treat)),
                 list(robust_se(m_saturate_trt))),
          type = 'text')
```

```{r f-test of variables for randomness}
anova(lm(treated ~ female + male + a18_24 + a25_34 + a35_44 + a45_54 + a55_64 + a65plus, 
         data=d),
      test = "F")
```

```{r t-test of variables for randomness with FACTORS}
#Estimate model
m_simple_treat <- lm(treated ~ factor(gender), 
         data=d)

m_saturate_trt <- lm(treated ~ factor(gender) + factor(age), 
         data=d)

#Print results
stargazer(m_simple_treat, m_saturate_trt, 
          se = c(list(robust_se(m_simple_treat)),
                 list(robust_se(m_saturate_trt))),
          type = 'text')
```

```{r f-test of variables for randomness WITH FACTOR}
anova(lm(treated ~ factor(gender) + factor(age), 
         data=d),
      test = "F")
```


```{r t-test of total observations}
#Estimate model
simple_m <- d[(gender != "unknown" & age != "unknown"), 
              lm(clicked ~ text + visual + textvisual)]

gender_m <- d[(gender != "unknown" & age != "unknown"), 
                 lm(clicked ~ text + visual + textvisual + female)]

saturated_m <- d[(gender != "unknown" & age != "unknown"), 
                 lm(clicked ~ text + visual + textvisual + female + 
                      a18_24 + a25_34 + a35_44 + a45_54 + a55_64)]
#Print results
stargazer(simple_m, gender_m, saturated_m,
          se = c(list(robust_se(simple_m)), 
                 list(robust_se(gender_m)),
                 list(robust_se(saturated_m))),
          type = 'text')
```

# Covariate Balance Check
Each covariate appears balanced across the four groups.

```{r covariate balance check}
#Balance check: Averages across control and treatment groups
cov_balance_checks <- d[, mean(clicked) * 100, by=.(group)]

#Balance check: Share of females across control and treatment groups
cov_balance_checks$share_female <- d[, sum(gender == 'female')/(.N), by=.(group)]$V1

#Balance check: Share of males across control and treatment groups
cov_balance_checks$share_male <- d[, sum(gender == 'male')/(.N), by=.(group)]$V1

#Balance check: Share of 18-24 year olds across control and treatment groups
cov_balance_checks$share_18_24 <- d[, sum(age == '18-24')/(.N), by=.(group)]$V1

#Balance check: Share of 25-34 year olds across control and treatment groups
cov_balance_checks$share_25_34 <- d[, sum(age == '25-34')/(.N), by=.(group)]$V1

#Balance check: Share of 35-44 year olds across control and treatment groups
cov_balance_checks$share_35_44 <- d[, sum(age == '35-44')/(.N), by=.(group)]$V1

#Balance check: Share of 45-54 year olds across control and treatment groups
cov_balance_checks$share_45_54 <- d[, sum(age == '45-54')/(.N), by=.(group)]$V1

#Balance check: Share of 55-64 year olds across control and treatment groups
cov_balance_checks$share_55_64 <- d[, sum(age == '55-64')/(.N), by=.(group)]$V1

#Balance check: Share of 65+ year olds across control and treatment groups
cov_balance_checks$share_65 <- d[, sum(age == '65+')/(.N), by=.(group)]$V1

#Balance check: Share of "unknown age" not necessary -- can subtract. 
head(cov_balance_checks)

```

# Covariate Balance Check Against Pilot Study
Mean clicks should look similar across groups for pilot study and full study. Covariates should also look similar.

```{r compare to pilot}
#Read in pilot data
pilot <- fread(file="../data/pilot_data.csv")
setnames(pilot, "Ad name", "group")
setnames(pilot, "Unique clicks (all)", "clicked")

#Balance check: Averages across control and treatment groups for pilot
pilot_balance_checks <- pilot[, 100*sum(clicked)/sum(Reach), by=.(group)]

#Balance check: Share of females across control and treatment groups for pilot
pilot_balance_checks$share_female <- pilot[Gender == 'female', sum(clicked), by=.(group)]$V1/pilot[, sum(clicked), by=.(group)]$V1

pilot_balance_checks
```

# Visualization

``` {r}
s <- d[age!='unknown', .(count=length(clicked)), by=.(age,group)]
ggplot(data= s, aes(x=age, y=count, fill=group)) + 
  geom_bar(stat='identity') +
  labs(x='Age Group', y='Count', fill='Ad type') +
  labs(title = "Age distribution, divided by ad assignment type")
```

``` {r}
t <- d[age!='unknown', .(count=length(clicked)), by=.(age, gender)]
ggplot(data= t, aes(x=age, y=count, fill=gender)) + 
  geom_bar(stat='identity') +
  labs(x='Age Group', y='Count', fill='Gender') +
  labs(title = "Age distribution, divided by gender") +
  scale_fill_manual(values = c("#DADAEB", "#9E9AC8", "#6A51A3"))
```
```{r}
u <- d[, .(count=length(clicked)), by=.(group, gender)]
ggplot(data= u, aes(x=group, y=count, fill=gender)) + 
  geom_bar(stat='identity') +
  labs(x='Treatment group', y='Count', fill="Gender") +
  labs(title = "Ad treatment distribution, divided by gender") +
  scale_fill_manual(values = c("#DADAEB", "#9E9AC8", "#6A51A3"))
```
